### PR TITLE
052-pip-clkin: Exclude potentially conflicting PIP + nodes from a run.

### LINKED ISSUE #783: Fuzzer 052-pip-clkin fails a lot in CI
There is a lot of routing errors in the 052 fuzzer e.g:

```
052-pip-clkin- 30m53s: Rolling back route
052-pip-clkin- 30m53s: Command: route_design -unroute -nets mynet_8
052-pip-clkin- 30m53s: Attempting to get a license for feature 'Implementation' and/or device 'xc7k70t-fbg676'
052-pip-clkin- 30m53s: INFO: [Common 17-349] Got license for feature 'Implementation' and/or device 'xc7k70t-fbg676'
052-pip-clkin- 30m53s: Command: report_drc (run_mandatory_drcs) for: incr_eco_checks
052-pip-clkin- 30m53s: INFO: [DRC 23-27] Running DRC with 8 threads
052-pip-clkin- 30m53s: report_drc (run_mandatory_drcs) completed successfully
052-pip-clkin- 30m53s: INFO: [Vivado_Tcl 4-198] DRC finished with 0 Errors
052-pip-clkin- 30m53s: INFO: [Vivado_Tcl 4-199] Please refer to the DRC report (report_drc) for more information.
052-pip-clkin- 30m53s: INFO: [Route 35-333] 1 net was fully unrouted.
052-pip-clkin- 30m53s: 18 Infos, 0 Warnings, 0 Critical Warnings and 0 Errors encountered.
052-pip-clkin- 30m53s: route_design completed successfully
052-pip-clkin- 30m53s: WARNING: failed to route net after 3 tries
052-pip-clkin- 30m53s: wrong # args: should be "error message ?errorInfo? ?errorCode?"
052-pip-clkin- 30m53s:     while executing
052-pip-clkin- 30m53s: "error"
052-pip-clkin- 30m53s:     invoked from within
052-pip-clkin- 30m53s: "if {$tries >= 3} {
052-pip-clkin- 30m53s:             puts "WARNING: failed to route net after $tries tries"
052-pip-clkin- 30m53s:             error
052-pip-clkin- 30m53s:         }"    
052-pip-clkin- 30m53s:     ("while" body line 38)
052-pip-clkin- 30m53s:     invoked from within
052-pip-clkin- 30m53s: "while {1} {
052-pip-clkin- 30m53s:         set tile_idx [expr $tries + [expr $idx * 3]]
052-pip-clkin- 30m53s:         incr tries
052-pip-clkin- 30m53s: 
052-pip-clkin- 30m53s:         if {$tile_type == "INT_L"} {set tile [lindex $int_l_tiles..."
052-pip-clkin- 30m53s:     ("for" body line 16)
052-pip-clkin- 30m53s:     invoked from within
052-pip-clkin- 30m53s: "for {set idx 0} {$idx < [llength $todo_lines]} {incr idx} {^
052-pip-clkin- 30m53s:     set line [lindex $todo_lines $idx]
052-pip-clkin- 30m53s:     puts "== $idx: $line"
052-pip-clkin- 30m53s: 
052-pip-clkin- 30m53s:     set tile_type [linde..."
052-pip-clkin- 30m53s:     (file "/tmpfs/src/github/symbiflow-prjxray-presubmit-db-kintex7/fuzzers/052-pip-clkin/generate.tcl" line 38)
```052-pip-clkin- 30m53s: Rolling back route
052-pip-clkin- 30m53s: Command: route_design -unroute -nets mynet_8
052-pip-clkin- 30m53s: Attempting to get a license for feature 'Implementation' and/or device 'xc7k70t-fbg676'
052-pip-clkin- 30m53s: INFO: [Common 17-349] Got license for feature 'Implementation' and/or device 'xc7k70t-fbg676'
052-pip-clkin- 30m53s: Command: report_drc (run_mandatory_drcs) for: incr_eco_checks
052-pip-clkin- 30m53s: INFO: [DRC 23-27] Running DRC with 8 threads
052-pip-clkin- 30m53s: report_drc (run_mandatory_drcs) completed successfully
052-pip-clkin- 30m53s: INFO: [Vivado_Tcl 4-198] DRC finished with 0 Errors
052-pip-clkin- 30m53s: INFO: [Vivado_Tcl 4-199] Please refer to the DRC report (report_drc) for more information.
052-pip-clkin- 30m53s: INFO: [Route 35-333] 1 net was fully unrouted.
052-pip-clkin- 30m53s: 18 Infos, 0 Warnings, 0 Critical Warnings and 0 Errors encountered.
052-pip-clkin- 30m53s: route_design completed successfully
052-pip-clkin- 30m53s: WARNING: failed to route net after 3 tries
052-pip-clkin- 30m53s: wrong # args: should be "error message ?errorInfo? ?errorCode?"
052-pip-clkin- 30m53s:     while executing
052-pip-clkin- 30m53s: "error"
052-pip-clkin- 30m53s:     invoked from within
052-pip-clkin- 30m53s: "if {$tries >= 3} {
052-pip-clkin- 30m53s:             puts "WARNING: failed to route net after $tries tries"
052-pip-clkin- 30m53s:             error
052-pip-clkin- 30m53s:         }"    
052-pip-clkin- 30m53s:     ("while" body line 38)
052-pip-clkin- 30m53s:     invoked from within
052-pip-clkin- 30m53s: "while {1} {
052-pip-clkin- 30m53s:         set tile_idx [expr $tries + [expr $idx * 3]]
052-pip-clkin- 30m53s:         incr tries
052-pip-clkin- 30m53s: 
052-pip-clkin- 30m53s:         if {$tile_type == "INT_L"} {set tile [lindex $int_l_tiles..."
052-pip-clkin- 30m53s:     ("for" body line 16)
052-pip-clkin- 30m53s:     invoked from within
052-pip-clkin- 30m53s: "for {set idx 0} {$idx < [llength $todo_lines]} {incr idx} {^
052-pip-clkin- 30m53s:     set line [lindex $todo_lines $idx]
052-pip-clkin- 30m53s:     puts "== $idx: $line"
052-pip-clkin- 30m53s: 
052-pip-clkin- 30m53s:     set tile_type [linde..."
052-pip-clkin- 30m53s:     (file "/tmpfs/src/github/symbiflow-prjxray-presubmit-db-kintex7/fuzzers/052-pip-clkin/generate.tcl" line 38)
```

this significantly impacts CI build time (see #774)

### PR DESCRIPTION
**Pull request by tmichalak**
Add several precautions to avoid specific routing attempts in the same Vivado run:
 1. Don't route a PIP with a destination or source wire already routed in this run
 2. Don't route to nodes with the X coordinate already routed in this run

Fixes #783.

Some parts of the routing paths done in the same vivado run for different PIPs were leftover and kept other specific PIPs from being routed properly.

### CODE REVIEW

**Comment by tmichalak** [comment]
I rerun the fuzzer 10 times and it didn't fail during routing as it used to.
Once #788 is merged I will rebase this PR and once it passes review and goes green it will be ready to merge.

**Comment by tmichalak** [comment]
The only slow fuzzer we have so far is 041-clk-hrow-pips and there is a separate issue #784 for it.
I would rather not make re-enabling it part of this PR and create a dedicated PR instead.
Is that ok?

**Comment by mithro** [comment]
I think I must have been looking at older changes. This looks okay.

You should update the title + description here to describe how you stabilized the fuzzer...

**Comment by tmichalak** [comment]
Hmm, I think I have done that a couple of minutes ago...
The title now says: "052-pip-clkin: stabilize and re-enable the fuzzer" and a description follows...

**Comment by mithro** [comment]
@tmichalak See how I updated the description and title. You should describe what is happening. "Stabilization" is not very descriptive.

**Pull request merged**
