### PR TITLE
Add simpleroute.py tool for routing signals through ROI

### PR DESCRIPTION
**Pull request by cliffordwolf**
Signed-off-by: Clifford Wolf <clifford@clifford.at>

### CODE REVIEW

**Comment by mcmasterg** [comment]
Merge this in once you run "make format" at top to fix formatting to be pep8

**Comment by cliffordwolf** [comment]
> "make format" ... to fix formatting to be pep8

Done. However, I must add that most of the changes introduced by this are not necessary for PEP 8 compliance. Furthermore, this removed extra blank lines that I used to group related blocks in a meaningful way, which is explicitly allowed by PEP 8.

If yapf formatting is required, fine. But then please lets not say it has anything to do with PEP 8. :) Afaict the only thing not PEP 8 compliant in the original code was long lines.

**Comment by mcmasterg** [comment]
Hhe okay. I'm just going along with what was setup. If you have objections to auto formatting stuff, you'll need to discuss that with the others

**Comment by cliffordwolf** [comment]
No, I'm not against using an autoformatter. I'm just saying that if this is what we do then let's not pretend its about PEP 8. Because then we should use a PEP 8 checker instead of an autoformatter.

For example, the current version of the coded uses multiple imports in one line, which is a violation of PEP 8. But apparently that's okay because we don't care about PEP 8, we care about yapfl.

On the other hand most of the changes performed by yapfl are stuff like this:

```
-for argidx in range((len(sys.argv)-1) // 2):
-    src_tile, src_wire = sys.argv[2*argidx+1].split("/")
-    dst_tile, dst_wire = sys.argv[2*argidx+2].split("/")
+for argidx in range((len(sys.argv) - 1) // 2):
+    src_tile, src_wire = sys.argv[2 * argidx + 1].split("/")
+    dst_tile, dst_wire = sys.argv[2 * argidx + 2].split("/")
```

But the original code here is perfectly fine with regard to PEP 8. So obviously PEP 8 is a red herring. That's all I wanted to point out.

**Comment by kc8apf** [comment]
I think the confusion comes from YAPF's configuration file declaring that our style is based on YAPF's PEP8 style.  I'm hearing you, say that YAPF's PEP8 style isn't strictly the minimum set of changes required by PEP8.

**Comment by cliffordwolf** [comment]
In addition to that: Other changes, that would be required by PEP 8 are not performed by the tool (such as multiple imports in one line). So "PEP 8" and "YAPF's PEP 8 style" are two different things, none is a subset of the other.

However, saying "this is because of PEP 8 compliance" gives something a certain ring of authority. But if in fact the changes requested have nothing to do with PEP 8 then it's just nonsensical namedropping. And that's sad because "we standardize on YAPF output" on it's own without even mentioning PEP 8 would of course be a perfectly sane position.

If however PEP 8 is the desired goal then YAPF is not the right tool imo. (I assume PEP 8 is not the goal and it's about canonical style and just about any autoformatter will do and I'm sure YAPF is a fine one.)

**Pull request merged**
