### PR TITLE
Minitest for PLLE2_ADV

### PR DESCRIPTION
**Pull request by mkurc-ant**
A minitest for the PLLE2_ADV. Multiple LEDs driven by PLL outputs.

### CODE REVIEW

**Comment by mkurc-ant** [comment]
When I ran bitstream of this design through `bit2vasm` I got some unknown bits. Seems to be CMT column related:

```
# In frame 0x0002009a 2 bits were not converted.
{ unknown_bit = "0002009a_50_27", unknown_segment = "0x00020080", unknown_segbit = "26_1627" }
{ unknown_bit = "0002009a_50_30", unknown_segment = "0x00020080", unknown_segbit = "26_1630" }

# In frame 0x0002009b 2 bits were not converted.
{ unknown_bit = "0002009b_50_26", unknown_segment = "0x00020080", unknown_segbit = "27_1626" }
{ unknown_bit = "0002009b_50_14", unknown_segment = "0x00020080", unknown_segbit = "27_1614" }

# In frame 0x0002009c 3 bits were not converted.
{ unknown_bit = "0002009c_50_19", unknown_segment = "0x00020080", unknown_segbit = "28_1619" }
{ unknown_bit = "0002009c_58_24", unknown_segment = "0x00020080", unknown_segbit = "28_1880" }
{ unknown_bit = "0002009c_59_27", unknown_segment = "0x00020080", unknown_segbit = "28_1915" }

# In frame 0x0002009d 6 bits were not converted.
{ unknown_bit = "0002009d_49_3", unknown_segment = "0x00020080", unknown_segbit = "29_1571" }
{ unknown_bit = "0002009d_50_18", unknown_segment = "0x00020080", unknown_segbit = "29_1618" }
{ unknown_bit = "0002009d_50_27", unknown_segment = "0x00020080", unknown_segbit = "29_1627" }
{ unknown_bit = "0002009d_50_28", unknown_segment = "0x00020080", unknown_segbit = "29_1628" }
{ unknown_bit = "0002009d_58_27", unknown_segment = "0x00020080", unknown_segbit = "29_1883" }
{ unknown_bit = "0002009d_59_27", unknown_segment = "0x00020080", unknown_segbit = "29_1915" }
```

**Comment by litghost** [comment]
> When I ran bitstream of this design through `bit2vasm` I got some unknown bits. Seems to be CMT column related:
> 
> ```
> # In frame 0x0002009a 2 bits were not converted.
> { unknown_bit = "0002009a_50_27", unknown_segment = "0x00020080", unknown_segbit = "26_1627" }
> { unknown_bit = "0002009a_50_30", unknown_segment = "0x00020080", unknown_segbit = "26_1630" }
> 
> # In frame 0x0002009b 2 bits were not converted.
> { unknown_bit = "0002009b_50_26", unknown_segment = "0x00020080", unknown_segbit = "27_1626" }
> { unknown_bit = "0002009b_50_14", unknown_segment = "0x00020080", unknown_segbit = "27_1614" }
> 
> # In frame 0x0002009c 3 bits were not converted.
> { unknown_bit = "0002009c_50_19", unknown_segment = "0x00020080", unknown_segbit = "28_1619" }
> { unknown_bit = "0002009c_58_24", unknown_segment = "0x00020080", unknown_segbit = "28_1880" }
> { unknown_bit = "0002009c_59_27", unknown_segment = "0x00020080", unknown_segbit = "28_1915" }
> 
> # In frame 0x0002009d 6 bits were not converted.
> { unknown_bit = "0002009d_49_3", unknown_segment = "0x00020080", unknown_segbit = "29_1571" }
> { unknown_bit = "0002009d_50_18", unknown_segment = "0x00020080", unknown_segbit = "29_1618" }
> { unknown_bit = "0002009d_50_27", unknown_segment = "0x00020080", unknown_segbit = "29_1627" }
> { unknown_bit = "0002009d_50_28", unknown_segment = "0x00020080", unknown_segbit = "29_1628" }
> { unknown_bit = "0002009d_58_27", unknown_segment = "0x00020080", unknown_segbit = "29_1883" }
> { unknown_bit = "0002009d_59_27", unknown_segment = "0x00020080", unknown_segbit = "29_1915" }
> ```

If I had to guess, this might be related to the BUFMR?  I don't think we've fuzzed that BEL yet.

**Comment by mkurc-ant** [comment]
That may be so. I had to use one BUFMR in the design.

**Comment by litghost** [comment]
> No, we have all bits for BUFR. But in this design I cannot have it without BUFMR because Vivado complains that it can't route across clock region.

Got it!

**Pull request merged**
