### PR TITLE
Enhanced 045 to solve FREQ_REF related PIPs

### PR DESCRIPTION
**Pull request by mkurc-ant**
This PR enhances 045 so it now can solve the following PIPs:
```
HCLK_CMT_FREQ_REF_NS0.HCLK_CMT_MUX_OUT_FREQ_REF0
HCLK_CMT_FREQ_REF_NS1.HCLK_CMT_MUX_OUT_FREQ_REF1
HCLK_CMT_FREQ_REF_NS2.HCLK_CMT_MUX_OUT_FREQ_REF2
HCLK_CMT_FREQ_REF_NS3.HCLK_CMT_MUX_OUT_FREQ_REF3
HCLK_CMT_MUX_OUT_FREQ_REF0.HCLK_CMT_CCIO0
HCLK_CMT_MUX_OUT_FREQ_REF0.HCLK_CMT_MUX_CLKINT_0
HCLK_CMT_MUX_OUT_FREQ_REF1.HCLK_CMT_CCIO1
HCLK_CMT_MUX_OUT_FREQ_REF1.HCLK_CMT_MUX_CLKINT_1
HCLK_CMT_MUX_OUT_FREQ_REF2.HCLK_CMT_CCIO2
HCLK_CMT_MUX_OUT_FREQ_REF2.HCLK_CMT_MUX_CLKINT_2
HCLK_CMT_MUX_OUT_FREQ_REF3.HCLK_CMT_CCIO3
HCLK_CMT_MUX_OUT_FREQ_REF3.HCLK_CMT_MUX_CLKINT_3
```

### CODE REVIEW

**Comment by litghost** [comment]
Still has a formatting error:
```
diff --git a/fuzzers/045-hclk-cmt-pips/Makefile b/fuzzers/045-hclk-cmt-pips/Makefile
index d3ff3eb..b817a28 100644
--- a/fuzzers/045-hclk-cmt-pips/Makefile
+++ b/fuzzers/045-hclk-cmt-pips/Makefile
@@ -10,7 +10,7 @@ EXCLUDE_RE="(^.*LEAF)|(^.*BUFMR)|(^.*PHSR)|(^.*CLK_PLL7)|(^.*CLK_MMCM13)"
 MAKETODO_FLAGS=--sides ",l" --pip-type ${PIP_TYPE} --seg-type ${PIP_TYPE} --re $(TODO_RE) --exclude-re $(EXCLUDE_RE)
 N = 100
 
-# All PIPs seem to have 2 bits. An exception is FREQ_REF which cannot be 
+# All PIPs seem to have 2 bits. An exception is FREQ_REF which cannot be
 # decoupled from the others, hence it will always have 4 bits.
 FOUR_BIT_PIPS="FREQ_REF"
```

**Comment by mkurc-ant** [comment]
Seems that I've lost `CCIOn_USED` bits. Investigating...

**Comment by mkurc-ant** [comment]
Likely not related to changes of this PR but it looks like an instability for Zynq 7:
```
Checking zynq7 database
============================
Checking individual .db...
segbits_*.db: 33 okay
mask_*.db: 39 okay
Checking aggregate dir...
ERROR: 1 collisions
  0040149a_016_27: had INT_R_X41Y58.INT_R.IMUX25.LOGIC_OUTS18, got CLBLM_R_X41Y58.CLBLM_R.SLICEL_X1.BLUT.INIT[16]
Traceback (most recent call last):
  File "utils/checkdb.py", line 181, in <module>
    main()
  File "utils/checkdb.py", line 177, in main
    run(args.db_root, args.part, verbose=args.verbose)
  File "utils/checkdb.py", line 163, in run
    check_tile_overlap(db, verbose=verbose)
  File "utils/checkdb.py", line 139, in check_tile_overlap
    raise ValueError("%s collisions" % len(collisions))
ValueError: 1 collisions
Makefile:154: recipe for target 'db-check-zynq7' failed
make: *** [db-check-zynq7] Error 1
```

**Comment by litghost** [comment]
`HCLK_CMT.HCLK_CMT_MUX_CLKINT_0_USED` look wrong to me.  Used bits are usually 1 bit, and the bits also show up a pip feature for `HCLK_CMT.HCLK_CMT_MUX_CLKINT_0_USED`.  I suspect there is no  `HCLK_CMT.HCLK_CMT_MUX_CLKINT_0_USED` feature?  Thoughts?

**Comment by mkurc-ant** [comment]
@litghost You're right, there are no separate bits for these features. I removed them.

One other thing that puzzles me is `CCIOn_USED`. These have separate bits but seem not to be enabled when a CCIO input is routed to a FREQ_REFn wire. I left them as they are.

**Pull request merged**
