### PR TITLE
htmlgen: use XRAY_ROI_TILEGRID instead of XRAY_ROI

### PR DESCRIPTION
**Pull request by acomodi**
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>

This PR fixes https://github.com/SymbiFlow/prjxray/issues/1264.

It changes to the usage of XRAY_ROI_TILEGRID instead of XRAY_ROI. This is more accurate as it corresponds to the whole device (or at least the one described by tilegrid.json). 

In addition XRAY_ROI_TILEGRID is mandatory to have in the settings files

### CODE REVIEW

**Comment by mithro** [comment]
LGTM.

**Comment by mithro** [comment]
@acomodi Can you look at getting htmlgen run as part of the CI for this repository?

**Comment by acomodi** [comment]
> @acomodi Can you look at getting htmlgen run as part of the CI for this repository?

Done, I have added it in Travis CI, as well as a script to run the htmlgen on all the setting files

**Comment by acomodi** [comment]
Hmm actually this won't work in Travis, unless I add also the download of the db in the script, to get the tilegrid info. Probably needs to be added in Kokoro?

**Comment by mithro** [comment]
@acomodi Kokoro or Travis is fine. Testing with `make download-db` could also be fine?

**Comment by acomodi** [comment]
@mithro Sure, I'll go with the make download-db solution then

**Comment by mithro** [comment]
Maybe as a separate travis build stage or something?

**Comment by acomodi** [comment]
So, re-thinking at this I would say that, in case there is a PR that adds an additional part, with a new tilegrid, the database would be incomplete, therefore the test would result in a failure. 
I believe we should add this test as a Kokoro stage at the end of the build

**Comment by mithro** [comment]
@acomodi Whatever you think is best.

**Comment by acomodi** [comment]
@mithro All the CI build went green. I see that Kintex and Tests CI are marked as still running, but they actually went green (unsure why this happens).

**Comment by mithro** [comment]
Okay merged it.

**Pull request merged**
