### PR TITLE
Add fuzzer for documenting pin to pad relationship for part.

### PR DESCRIPTION
**Pull request by litghost**
Signed-off-by: Keith Rothman <537074+litghost@users.noreply.github.com>

### CODE REVIEW

**Comment by mithro** [comment]
What does the output look like?

**Comment by litghost** [comment]
```
pin,site,tile
M9,IPAD_X0Y1,MONITOR_BOT_X46Y79
L10,IPAD_X0Y0,MONITOR_BOT_X46Y79
P20,IOB_X0Y49,LIOB33_SING_X0Y49
P22,IOB_X0Y48,LIOB33_X0Y47
```

**Comment by mithro** [comment]
The only other CSV file we have in the database is the `elements_count.csv`. Should we be using JSON here instead?

**Comment by litghost** [comment]
> The only other CSV file we have in the database is the `elements_count.csv`. Should we be using JSON here instead?

JSON seems unnecessary here, and complicates the fuzzer output.  There isn't structure, so a simple flat CSV seems fine.

**Pull request merged**
