### PR TITLE
infra: Collect Vivado logs into tgz archive

### PR DESCRIPTION
**Pull request by tmichalak**
Signed-off-by: Tomasz Michalak <tmichalak@antmicro.com>
This PR is to solve #785

### CODE REVIEW

**Comment by tmichalak** [comment]
I see from the first runs that due to the failure in the execution we don't get to the part of the script responsible for collecting the logs: https://github.com/SymbiFlow/prjxray/blob/ddc65e19336fce93c36b38f006c15cccd5fcab74/.github/kokoro/db-full.sh#L62
I could work around it in bash using ``set -e``, but I wonder if there is a builtin feature in kokoro that makes it possible to define a on-failure action or script.

**Comment by mithro** [comment]
You need to run the `.github/kokoro/kokoro-cfg.py` script and commit the changes.

**Comment by tmichalak** [comment]
I can see from the logs of all 3 fails that the vivado logs were generated. However, the tgz archive is nowhere to find?

**Comment by litghost** [comment]
They can be found in GCS: https://pantheon.corp.google.com/storage/browser/symbiflow-prjxray/artifacts/prod/foss-fpga-tools/prjxray/presubmit/database/artix7/328/20190418-051921/fuzzers/

**Comment by mithro** [comment]
Looking [Invocation Details](https://source.cloud.google.com/results/invocations/8d18f9b0-4db0-4675-b1a9-37232176edea/details) tab you will find a link to [GCS](https://console.cloud.google.com/storage/browser/symbiflow-prjxray/artifacts/prod/foss-fpga-tools/prjxray/presubmit/database/artix7/328/20190418-051921).

Find [vivado.tgz for artix7](https://storage.cloud.google.com/symbiflow-prjxray/artifacts/prod/foss-fpga-tools/prjxray/presubmit/database/artix7/328/20190418-051921/fuzzers/vivado.tgz?_ga=2.67209745.-1641220752.1541359374).

**Pull request merged**
