### PR TITLE
BEL timings fixes

### LINKED ISSUE #832: bel timing fuzzer does not emit all the timing dumped from vivado
Some of the timings are present in the timings_dump txt file, but the are not present in the sdfs

### LINKED ISSUE #833: bel timings sdf have 1ps timescale, while should have 1ns

### LINKED ISSUE #834: sdf merge emits all the instances of the cells
sdf merge tool should emit only selected instance of the processed cells. Right now it emits all the instances e.g. in slicel.sdf both SLICEL and SLICEM instances are present

### PR DESCRIPTION
**Pull request by kgugala**
fixes #832 
fixes #833 
fixes #834

### CODE REVIEW

**Comment by mithro** [comment]
FYI - Canonicalizing / stable ordering of the SDF file is logged as https://github.com/SymbiFlow/prjxray/issues/815

**Comment by kgugala** [comment]
@litghost #836 adds sdf sorting. When merged I'll rebase this PR so the results are more readable

**Comment by mithro** [comment]
I rebased this on top of origin/master so we can look at the kokoro output...

**Comment by kgugala** [comment]
CI is red due to Vivado's segfault:

```
2019-05-15T02:08:59.772999 - 045-hclk-cmt-pips        - 1h22m: /opt/Xilinx/Vivado/2017.2/bin/loader: line 179: 76658 Segmentation fault      "$RDI_PROG" "$@"
2019-05-15T02:08:59.772999 - 045-hclk-cmt-pips        - 1h22m: make[3]: *** [vivado.ok] Error 139
2019-05-15T02:08:59.772999 - 045-hclk-cmt-pips        - 1h22m: make[2]: *** [build/6/specimen_087/OK] Error 2
2019-05-15T02:08:59.772999 - 045-hclk-cmt-pips        - 1h22m: make[2]: *** Waiting for unfinished jobs....
2019-05-15T02:08:59.772999 - 045-hclk-cmt-pips        - 1h22m: make[1]: *** [run] Error 2
```
I'll restart the tests

**Comment by litghost** [comment]
Thanks for the clean diffs, I can review now!

```
    (CELL
        (CELLTYPE "FF_INIT")
        (INSTANCE SLICEL)
        (DELAY
            (ABSOLUTE
                (IOPATH CLK Q (0.099::0.124)(0.244::0.303))
            )
        )
        (TIMINGCHECK
            (HOLD CE (posedge CLK) (-0.011::-0.009))
            (HOLD DIN (posedge CLK) (0.181::0.225))
            (SETUP CE (posedge CLK) (0.088::0.109))
            (SETUP DIN (posedge CLK) (-0.057::-0.046))
        )
    )
    (CELL
        (CELLTYPE "FF_INIT_INIT")
        (INSTANCE SLICEL)
        (TIMINGCHECK
            (HOLD CLK (posedge CLK) (-0.074::-0.060))
            (SETUP CLK (posedge CLK) (0.345::0.428))
        )
    )
```
"CELLTYPE FF_INIT_INIT" is wrong.  I believe that this setup and hold constrain should be part of the celltype above, FF_INIT.  They should be setup and hold from INIT to CLK.

**Comment by litghost** [comment]
Something that was working before is now wrong in CELLTYPE "LUT_OR_MEM5LRAM":
```
    (CELL
        (CELLTYPE "LUT_OR_MEM5LRAM")
        (INSTANCE SLICEM)
        (TIMINGCHECK
            (HOLD CLK (posedge CLK) (0.728::0.538))
            (SETUP CLK (posedge CLK) (0.184::0.066))
            (HOLD CLK (posedge CLK) (0.745::0.572))
            (SETUP CLK (posedge CLK) (0.181::0.068))
            (HOLD CLK (posedge CLK) (0.579::0.460))
            (SETUP CLK (posedge CLK) (0.214::0.147))
            (HOLD CLK (posedge CLK) (0.507::0.411))
            (SETUP CLK (posedge CLK) (0.248::0.208))
            (HOLD WA5 (posedge CLK) (0.332::0.314))
            (SETUP WA5 (posedge CLK) (0.236::0.245))
            (HOLD CLK (posedge CLK) (0.008::0.010))
            (SETUP CLK (posedge CLK) (0.527::0.654))
        )
```

**Comment by litghost** [comment]
Overall, this PR improves many of the names on the setup/hold constraints, just some remaining edge cases to clean up.

**Comment by kgugala** [comment]
I have also updated the `python-sdf-timing` lib so it produces sorted sdfs https://github.com/SymbiFlow/python-sdf-timing/pull/28

**Comment by kgugala** [comment]
@litghost the latest changes should fix the issues you pointed, please check the results when they are available

**Comment by litghost** [comment]
> @litghost the latest changes should fix the issues you pointed, please check the results when they are available

I'll take a look once the new database run is complete.

**Comment by kgugala** [comment]
@litghost the dbs are now built

**Comment by litghost** [comment]
Why are there only 2 values for the setup/hold constraints?  I would expect 4 for FAST_MIN/MAX, SLOW_MIN/MAX?

**Comment by kgugala** [comment]
> Why are there only 2 values for the setup/hold constraints? I would expect 4 for FAST_MIN/MAX, SLOW_MIN/MAX?

This is an sdf limitation. See page 30 of the attached doc.
[doc_sdf.pdf](https://github.com/SymbiFlow/prjxray/files/3189878/doc_sdf.pdf)

**Pull request merged**
