### PR TITLE
download-latest: clean files

### PR DESCRIPTION
**Pull request by mcmasterg**
This streamlines getting a cached DB while still doing fuzzer development

### CODE REVIEW

**Comment by mcmasterg** [comment]
We are deleting the misc files, not the .db files

**Comment by mcmasterg** [comment]
I should also add this has bothered me for a while, but is causing more serious problems with people trying to get started

**Comment by mithro** [comment]
I think the correct solution is to move `settings.sh` files out of the database directory and then `.gitignore` the whole `database` directory?

**Comment by mithro** [comment]
It does seem a bit silly to have the `settings.sh` inside the database?

**Comment by mcmasterg** [comment]
you are probably correct in that is the proper fix. But I'd rather not mess with that right now while we have people to work with

**Comment by mcmasterg** [comment]
Filed https://github.com/SymbiFlow/prjxray/issues/421

**Pull request merged**
