### PR TITLE
remove MAP_POPULATE

### PR DESCRIPTION
**Pull request by HackerFoo**
An alternate PR for https://github.com/SymbiFlow/prjxray/pull/1360

### CODE REVIEW

**Comment by HackerFoo** [comment]
Strange. It [failed an assertion](https://source.cloud.google.com/results/invocations/3ddb3a85-818e-44f5-a595-a600df236b25/targets/foss-fpga-tools%2Fprjxray%2Fpresubmit%2Fdatabase%2Fzynq7/log), even though this change should have no functional effect:

```
2020-06-11T20:20:38 - xc7z020clg484-1/052-pip-clkin             - 3h02m:   File "/tmpfs/src/github/symbiflow-prjxray-presubmit-db-zynq7/prjxray/tile_segbits.py", line 71, in read_segbits
2020-06-11T20:20:38 - xc7z020clg484-1/052-pip-clkin             - 3h02m:     assert len(parts) > 1
2020-06-11T20:20:38 - xc7z020clg484-1/052-pip-clkin             - 3h02m: AssertionError
```

**Comment by litghost** [comment]
> Strange. It [failed an assertion](https://source.cloud.google.com/results/invocations/3ddb3a85-818e-44f5-a595-a600df236b25/targets/foss-fpga-tools%2Fprjxray%2Fpresubmit%2Fdatabase%2Fzynq7/log), even though this change should have no functional effect:
> 
> ```
> 2020-06-11T20:20:38 - xc7z020clg484-1/052-pip-clkin             - 3h02m:   File "/tmpfs/src/github/symbiflow-prjxray-presubmit-db-zynq7/prjxray/tile_segbits.py", line 71, in read_segbits
> 2020-06-11T20:20:38 - xc7z020clg484-1/052-pip-clkin             - 3h02m:     assert len(parts) > 1
> 2020-06-11T20:20:38 - xc7z020clg484-1/052-pip-clkin             - 3h02m: AssertionError
> ```

Ya, that's super weird.  Latent bug?

**Comment by litghost** [comment]
Looks like dropping POPULATE causes the Zynq CI to take ~40 minutes longer.  Let's see if Artix shows a similar jump.  If so, we'll use #1360

**Comment by litghost** [comment]
CI failure is due to an unrelated change, working on a revert now.

**Comment by litghost** [comment]
Looks like there was no ill affect removing the flag, lets simply drop it.

**Pull request merged**
