### PR TITLE
Fixup OSERDES features to handle missing bits

### PR DESCRIPTION
**Pull request by litghost**
May help with https://github.com/SymbiFlow/symbiflow-arch-defs/issues/1307 or https://github.com/SymbiFlow/symbiflow-arch-defs/issues/1536

### CODE REVIEW

**Comment by mkurc-ant** [comment]
Strange: `X-Ray (Presubmit)` says that: `foss-fpga-tools/prjxray/presubmit/tests finished with status: FAILED`. But the check `X-Ray (Presubmit) - Tests` actually passed.

**Comment by litghost** [comment]
I did some more testing and found some issues with this PR.  Still investigating solutions.

**Comment by litghost** [comment]
> I did some more testing and found some issues with this PR. Still investigating solutions.

I believe I've fixed the issues I discovered.

**Review by mkurc-ant — APPROVED** [review]
Ok, LGTM

**Pull request merged**
