### PR TITLE
Try running DSP fuzzers on Kintex7.

### PR DESCRIPTION
**Pull request by mithro**
Signed-off-by: Tim 'mithro' Ansell <tansell@google.com>

### CODE REVIEW

**Comment by mithro** [comment]
Creating a WIP pull request to test if the DSP fuzzer really does break on Kintex7 or not...

**Comment by mithro** [comment]
FYI -- @mkurc-ant / @acomodi / @tmichalak

**Comment by mithro** [comment]
@acomodi / @mkurc-ant - This seems to indicate that the DSP fuzzers work on Kintex 7 parts?

**Comment by tmichalak** [comment]
It certainly looks like the DSP fuzzer does work. It might be unstable though and doesn't work every time...

**Review by acomodi — APPROVED** [review]
LGTM, CI went green. In general, tilegrid fuzzers should be quite stable, and repeatable, it is more common to see instability in PIPs fuzzers instead.

**Pull request merged**
