### PR TITLE
Fix python on kokoro and break circular import through tile_segbits.

### PR DESCRIPTION
**Pull request by litghost**
@mkurc-ant This probably needs to be fixed in prjuray-tools too.  Another reason to converge the repos when we can.

### CODE REVIEW

**Comment by mkurc-ant** [comment]
@litghost Good catch. I've issued a similar PR to prjuray-tools.

**Review by mithro — APPROVED** [review]
Generally LGTM.

BTW Are we requiring Python 3.8 now? If so that should be in the README right?

**Comment by litghost** [comment]
> Generally LGTM.
> 
> BTW Are we requiring Python 3.8 now? If so that should be in the README right?

We only really need Python 3.6, and the Xeniel default is Python 3.5.  We don't specifically require Python 3.5 really, but `python3.5 -mpip install numpy` now generates the error:

```
Collecting numpy (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/2c/2f/7b4d0b639a42636362827e611cfeba67975ec875ae036dd846d459d52652/numpy-1.19.1.zip (7.3MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmpfs/tmp/pip-build-4efh__zv/numpy/setup.py", line 30, in <module>
        raise RuntimeError("Python version >= 3.6 required.")
    RuntimeError: Python version >= 3.6 required.
```

**Comment by mithro** [comment]
We could potentially just move to bionic?

**Comment by litghost** [comment]
Looks like the newer python consistently results in a DB conflict, investigating.

**Comment by litghost** [comment]
> Looks like the newer python consistently results in a DB conflict, investigating.

I've replicated the issue locally, and have a proposed fix.  We'll see if it works on the CI.

**Pull request merged**
