### PR TITLE
segmatch.cpp: if f_in does not exits returns -1

### PR DESCRIPTION
**Pull request by acomodi**
This PR is to get en error if segmatch does not find the input file as suggested in https://github.com/SymbiFlow/prjxray/pull/630. This solves https://github.com/SymbiFlow/prjxray/issues/338

Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>

### CODE REVIEW

**Comment by litghost** [comment]
Please rebase this PR on master and push to let presubmit database build with this change against latest fuzzers.

**Comment by litghost** [comment]
```
Reading build/specimen_002/segdata_hclk_l_design_*.txt.
ERROR: Input file does not exist!
```

This PR breaks 058, or exposes an issue in how it was written.

**Comment by acomodi** [comment]
Yes, most probably there is an issue in how the fuzzer is written. I guess it is required that a file is present as input for segmatch

**Comment by litghost** [comment]
> Yes, most probably there is an issue in how the fuzzer is written. I guess it is required that a file is present as input for segmatch

The fuzzer was written such that specimen_001 is only HCLK_L and specimen_002 is HCLK_R, hence why one has segdata.  A find invocation should resolve that?

**Comment by acomodi** [comment]
Yes, that'll solve the issue

**Comment by acomodi** [comment]
Fixes https://github.com/SymbiFlow/prjxray/issues/338.

**Pull request merged**
