### PR TITLE
007-timing: Do not emit SDF files for sites with no timings.

### LINKED ISSUE #814: Figure out what to do with "empty" SDF files for tiles.
The hash of fdbd15cd9a5b54d402980d250333c7ab8bdbff2f89eaffbc8053e1afde4dbfd5 is because of a large number of "empty" files like this;
```
            
            (DELAYFILE            
                (SDFVERSION "3.0")            
                (TIMESCALE 1ps)            
            
            )
```

These files are empty;
 * [`./artix7/timings/BRAM_INT_INTERFACE_L.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/BRAM_INT_INTERFACE_L.sdf)
 * [`./artix7/timings/BRAM_INT_INTERFACE_R.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/BRAM_INT_INTERFACE_R.sdf)
 * [`./artix7/timings/BRAM_L.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/BRAM_L.sdf)
 * [`./artix7/timings/BRAM_R.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/BRAM_R.sdf)
 * [`./artix7/timings/BRKH_BRAM.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/BRKH_BRAM.sdf)
 * [`./artix7/timings/BRKH_B_TERM_INT.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/BRKH_B_TERM_INT.sdf)
 * [`./artix7/timings/BRKH_CLB.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/BRKH_CLB.sdf)
 * [`./artix7/timings/BRKH_CLK.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/BRKH_CLK.sdf)
 * [`./artix7/timings/BRKH_CMT.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/BRKH_CMT.sdf)
 * [`./artix7/timings/BRKH_DSP_L.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/BRKH_DSP_L.sdf)
 * [`./artix7/timings/BRKH_DSP_R.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/BRKH_DSP_R.sdf)
 * [`./artix7/timings/BRKH_GTX.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/BRKH_GTX.sdf)
 * [`./artix7/timings/BRKH_INT.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/BRKH_INT.sdf)
 * [`./artix7/timings/BRKH_TERM_INT.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/BRKH_TERM_INT.sdf)
 * [`./artix7/timings/B_TERM_INT.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/B_TERM_INT.sdf)
 * [`./artix7/timings/CFG_CENTER_BOT.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/CFG_CENTER_BOT.sdf)
 * [`./artix7/timings/CLK_BUFG_BOT_R.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/CLK_BUFG_BOT_R.sdf)
 * [`./artix7/timings/CLK_BUFG_REBUF.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/CLK_BUFG_REBUF.sdf)
 * [`./artix7/timings/CLK_BUFG_TOP_R.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/CLK_BUFG_TOP_R.sdf)
 * [`./artix7/timings/CLK_FEED.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/CLK_FEED.sdf)
 * [`./artix7/timings/CLK_MTBF2.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/CLK_MTBF2.sdf)
 * [`./artix7/timings/CLK_PMV.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/CLK_PMV.sdf)
 * [`./artix7/timings/CLK_PMV2.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/CLK_PMV2.sdf)
 * [`./artix7/timings/CLK_PMV2_SVT.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/CLK_PMV2_SVT.sdf)
 * [`./artix7/timings/CLK_PMVIOB.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/CLK_PMVIOB.sdf)
 * [`./artix7/timings/CLK_TERM.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/CLK_TERM.sdf)
 * [`./artix7/timings/CMT_PMV.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/CMT_PMV.sdf)
 * [`./artix7/timings/CMT_PMV_L.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/CMT_PMV_L.sdf)
 * [`./artix7/timings/GTP_INT_INTERFACE.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/GTP_INT_INTERFACE.sdf)
 * [`./artix7/timings/HCLK_BRAM.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/HCLK_BRAM.sdf)
 * [`./artix7/timings/HCLK_CLB.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/HCLK_CLB.sdf)
 * [`./artix7/timings/HCLK_DSP_L.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/HCLK_DSP_L.sdf)
 * [`./artix7/timings/HCLK_DSP_R.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/HCLK_DSP_R.sdf)
 * [`./artix7/timings/HCLK_FEEDTHRU_1.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/HCLK_FEEDTHRU_1.sdf)
 * [`./artix7/timings/HCLK_FEEDTHRU_2.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/HCLK_FEEDTHRU_2.sdf)
 * [`./artix7/timings/HCLK_FIFO_L.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/HCLK_FIFO_L.sdf)
 * [`./artix7/timings/HCLK_GTX.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/HCLK_GTX.sdf)
 * [`./artix7/timings/HCLK_INT_INTERFACE.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/HCLK_INT_INTERFACE.sdf)
 * [`./artix7/timings/HCLK_IOB.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/HCLK_IOB.sdf)
 * [`./artix7/timings/HCLK_L.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/HCLK_L.sdf)
 * [`./artix7/timings/HCLK_L_BOT_UTURN.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/HCLK_L_BOT_UTURN.sdf)
 * [`./artix7/timings/HCLK_R.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/HCLK_R.sdf)
 * [`./artix7/timings/HCLK_R_BOT_UTURN.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/HCLK_R_BOT_UTURN.sdf)
 * [`./artix7/timings/HCLK_TERM.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/HCLK_TERM.sdf)
 * [`./artix7/timings/HCLK_TERM_GTX.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/HCLK_TERM_GTX.sdf)
 * [`./artix7/timings/HCLK_VBRK.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/HCLK_VBRK.sdf)
 * [`./artix7/timings/HCLK_VFRAME.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/HCLK_VFRAME.sdf)
 * [`./artix7/timings/INT_FEEDTHRU_1.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/INT_FEEDTHRU_1.sdf)
 * [`./artix7/timings/INT_FEEDTHRU_2.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/INT_FEEDTHRU_2.sdf)
 * [`./artix7/timings/INT_INTERFACE_L.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/INT_INTERFACE_L.sdf)
 * [`./artix7/timings/INT_INTERFACE_R.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/INT_INTERFACE_R.sdf)
 * [`./artix7/timings/INT_L.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/INT_L.sdf)
 * [`./artix7/timings/INT_R.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/INT_R.sdf)
 * [`./artix7/timings/IO_INT_INTERFACE_L.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/IO_INT_INTERFACE_L.sdf)
 * [`./artix7/timings/IO_INT_INTERFACE_R.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/IO_INT_INTERFACE_R.sdf)
 * [`./artix7/timings/L_TERM_INT.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/L_TERM_INT.sdf)
 * [`./artix7/timings/MONITOR_MID.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/MONITOR_MID.sdf)
 * [`./artix7/timings/MONITOR_TOP.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/MONITOR_TOP.sdf)
 * [`./artix7/timings/PCIE_INT_INTERFACE_L.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/PCIE_INT_INTERFACE_L.sdf)
 * [`./artix7/timings/PCIE_INT_INTERFACE_R.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/PCIE_INT_INTERFACE_R.sdf)
 * [`./artix7/timings/PCIE_NULL.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/PCIE_NULL.sdf)
 * [`./artix7/timings/PCIE_TOP.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/PCIE_TOP.sdf)
 * [`./artix7/timings/R_TERM_INT.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/R_TERM_INT.sdf)
 * [`./artix7/timings/R_TERM_INT_GTX.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/R_TERM_INT_GTX.sdf)
 * [`./artix7/timings/TERM_CMT.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/TERM_CMT.sdf)
 * [`./artix7/timings/T_TERM_INT.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/T_TERM_INT.sdf)
 * [`./artix7/timings/VBRK.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/VBRK.sdf)
 * [`./artix7/timings/VBRK_EXT.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/VBRK_EXT.sdf)
 * [`./artix7/timings/VFRAME.sdf`](https://github.com/SymbiFlow/prjxray-db/tree/master/artix7/timings/VFRAME.sdf)

### PR DESCRIPTION
**Pull request by kgugala**
fixes #814

### CODE REVIEW

**Comment by mithro** [comment]
Hrm, I'm not sure why Kokoro isn't running the database builds?

**Comment by kgugala** [comment]
@mithro the dbs were built

**Comment by mithro** [comment]
Looking at the patch result. It doesn't look like there are a lot less SDF files?

**Comment by mithro** [comment]
[Diff output](https://00e9e64bacc193710cd705c8ea241530bacd7052f7d6267c76-apidata.googleusercontent.com/download/storage/v1/b/symbiflow-prjxray/o/artifacts%2Fprod%2Ffoss-fpga-tools%2Fprjxray%2Fpresubmit%2Fdatabase%2Fartix7%2F591%2F20190613-115219%2Fdatabase%2Fdiff.html?qk=AD5uMEuzgxzpewXwSLVMYgHE7zPFnj_BzLd4A13ESCBcHAOaesnym31L0zaRlI1Z0ZR5jXAOETvEYzYXZcscTUGWp3cgOwwK9P6u1GLddfl5X9Ic4fRgyShLzdKkh3JRINASFcs6kK4btf9RZfqWbxjzpFuS1ObuH5T8fgnMsmL6iGfJuv96_w8myKwFO2KBOE6ChoVRGkbX12DyPTzjvhurjGAJ78U3MLp0BIyWmAlcAtWEfmfmu6BfCm_KZJ0muY4ArBLwfqvskNVe18ZS7woqnu_U8Cm90rHAy8DIiTLVLVjpznRF4CMWEgPxFwR6OqPgnxrKHZfYEY8fsUZ9i1vU3hav06tWwGqftkUtbV08BzG4EdjHTuHbm-Khs31aKQjkfsLVW3HDbJRoCFsSlb5zqTorglM8wWsyrfH9fRXEsxvA0iCZOHxNJe449Xtr2M1nWICQAra0ehXLaiPIq-ZELbcgR6Z183KHOH6W-2hXDKKlELJe-H8U_Pq87oQkBqY_zbicZij7tr7Bf1bqbTzeB6jauuJgollEsUwZZM29D0T6oFnpq0Ad9cHQwNPFGSibiD_kfdV54E9KDfyY3jiYweDuvymYJ8ebBWFm7-alyzPyd0fs7isNe3Au5x_ETCj7FWbYn40XBNR1TMMGI5Fsf9IsJM0p47mIZZTYeoMqMJSsLw6bPL-c_zLB99ADnLVEHmvpPlBsVN2AU0XpuEO3wcVIyaJ7I3AqU9XGiGAFgmlc4rqNkuZy4H0v5ru9iLpuAMOIkheDBMyWwWx7V9SvXsMdk8H8m7Ber2U8bho9HmajzM9CQ02ZlXXbJwQBltd1X7neE5sEKl1i3N0wFQgPeqMbVHTnTAumFBK95-EaCcPSE7VMIL8mfZlevkUMrxhq9SzZzhT0qsUqKVSg-G_Ge1QQ703q4fWJOs8Ucfb18fVTMHspsJM)

**Comment by kgugala** [comment]
the diff link gives me:

`{"error":{"errors":[{"domain":"global","reason":"lockedDomainExpired","message":"Locked Domain Expired"}],"code":401,"message":"Locked Domain Expired"}}`

**Comment by mithro** [comment]
Try this URL? https://console.cloud.google.com/storage/browser/symbiflow-prjxray/artifacts/prod/foss-fpga-tools/prjxray/presubmit/database/artix7/591/20190613-115219/database

**Comment by kgugala** [comment]
clean-db target was not removing the old sdf files. It should be fixed now. Let's wait for new DB

**Comment by kgugala** [comment]
@mithro the DB now seems to have only relevant files

**Pull request merged**
