### PR TITLE
054-pip-fan-alt: add BYP_ALT.GFAN PIPs calculation to fuzzer

### PR DESCRIPTION
**Pull request by tmichalak**
Signed-off-by: Tomasz Michalak <tmichalak@antmicro.com>
This PR is part of the Stabilize prjxray output project
It is aimed at solving #567

### CODE REVIEW

**Comment by tmichalak** [comment]
Changed to WIP as this needs to be rerun rebased on the "clean" master with PR #788 merged.

**Comment by mithro** [comment]
This will need to be rebased on top of master.

**Comment by tmichalak** [comment]
The CI is green after rebasing it on top of the current master. I reran this branch locally 10 times with checkdb at the end and everything was ok.
I am not 100% certain that this problem will not reappear once we reenable the rest of the currently disabled fuzzers.

**Comment by mithro** [comment]
This pull request seems to have solved https://github.com/SymbiFlow/prjxray/issues/567

**Pull request merged**
