### PR TITLE
Fix wrong parameter in get_part_resources()

### PR DESCRIPTION
**Pull request by MidsummerNight**
The assertion error for `get_part_resources()` should print `res_mapping` instead of `part_mapping` (the latter isn't even defined in `get_part_resources()`). See #1834 for details.

### CODE REVIEW

**Comment by acomodi** [comment]
@MidsummerNight Thanks for this fix!

There is the DCO check failing (https://stackoverflow.com/questions/25570947/how-to-use-git-interactive-rebase-for-signing-off-a-series-of-commits).

On an additional note the usual workflow is to:
- create a new branch starting from the upstream master one
- from the branch open the PR
- if any update lands on upstream master, `rebase` the branch on top of it

**Comment by acomodi** [comment]
@MidsummerNight Sign off should be applied to all commits in the PR. Actually I think you could squash all of them into a single commit (https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git)

**Comment by MidsummerNight** [comment]
Ugh somehow Tim's Kintex commit got inside......

**Comment by MidsummerNight** [comment]
I ran `gh pr checkout 1835`, then `git rebase HEAD~5 --signoff` followed by `git push --force-with-lease origin master` as the DCO check page told me. Maybe I should've used `HEAD~4` instead of 5...

**Comment by acomodi** [comment]
I think you may create a new branch from the current [HEAD](https://github.com/SymbiFlow/prjxray/commit/5349556bc2c230801d6df0cf11bccb9cfd171639), commit your change with the sign-off and open a new PR

**Comment by MidsummerNight** [comment]
Yeah that would be a better way. Will do more research on Git and create a new PR tomorrow.

**Comment by MidsummerNight** [comment]
Filed #1836 with correct sign-off to replace this one. I'll make sure to always sign off properly in future PRs.

**Pull request closed without merging**
