### PR TITLE
WIP: adding DSP for FAN_ALTs and BYPs to 050-pip-seed 

### PR DESCRIPTION
**Pull request by acomodi**
I am still running the build but it seems that all the FAN_ALT?.GFAN? are being correctly solved.

This is to solve https://github.com/SymbiFlow/prjxray/issues/611 and https://github.com/SymbiFlow/prjxray/issues/567

Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>

### CODE REVIEW

**Comment by acomodi** [comment]
The fuzzer correctly solves some of the FAN_ALT?.GFAN? pips, but not all of them. I am trying to do another build with a `min_progress` set to a lower value, because the build finished after iteration `3`. Probably I will need to add some other features to the `DSP` to get all the remaining FAN_ALT pips

**Comment by litghost** [comment]
> The fuzzer correctly solves some of the FAN_ALT?.GFAN? pips, but not all of them. I am trying to do another build with a `min_progress` set to a lower value, because the build finished after iteration `3`. Probably I will need to add some other features to the `DSP` to get all the remaining FAN_ALT pips

Update https://github.com/SymbiFlow/prjxray/blob/master/fuzzers/050-pip-seed/Makefile#L87 to include "FAN_ALT?.GFAN?" in the required solution set.

So something like "--zero-entries-filter (IMUX.*GFAN)|(FAN_ALT.\.GFAN)"

**Comment by litghost** [comment]
Looks like you are close, FAN_ALT1.GFAN1 is missing stimulus thought:

```
grep "FAN_ALT.*GFAN" 050-pip-seed/build/1/segbits_int_l.db 
INT.FAN_ALT0.GFAN0 <m1 6> 21_00 25_00
INT.FAN_ALT1.GFAN1 <m1 0> <const0>
INT.FAN_ALT2.GFAN0 <m1 2> 21_16 25_16
INT.FAN_ALT3.GFAN1 <8 candidates>
INT.FAN_ALT4.GFAN0 <m1 7> 21_08 25_08
INT.FAN_ALT5.GFAN1 <m1 1> 00_20 01_43 21_40 25_40
INT.FAN_ALT6.GFAN0 <m1 8> 21_24 25_24
INT.FAN_ALT7.GFAN1 21_32 25_32
```

**Comment by acomodi** [comment]
Yeah, but it should get solved in the other iterations

**Comment by litghost** [comment]
Looks like it wont, at least on artix7.

**Comment by litghost** [comment]
> Looks like it wont, at least on artix7.

The reason for this is that all DSP tile within the ROI are DSP_R, so the INT_R solution converges with this PR, but not the DSP_L solution.  If I fix #566, then all INT tiles will have base addresses, and then including some DSP_L should make this work plus adding the change to the zero entries regexp.

I'm working on #566, half way done.

**Comment by acomodi** [comment]
Yeah, unfortunately there is only one DSP column in the actual ROI. Anyway maybe I should produce more stimulus to be sure to get all those pips

**Comment by litghost** [comment]
I'm running a test removing the ROI on a7, I expect it to solve all of the FAN_ALT?.GFAN? pips.  If so, that is the simplest answer.

**Comment by litghost** [comment]
> I'm running a test removing the ROI on a7, I expect it to solve all of the FAN_ALT?.GFAN? pips. If so, that is the simplest answer.

Experiment failed.  I think what is happening is that the DSP is not providing the expected stimulus because it is using the internal DSP TIEOFF block, rather than the INT tile TIEOFF block.  DSP was maybe not a good choice :/

**Comment by acomodi** [comment]
With the latest build I have produced almost all the FAN_ALT.GFANs (FAN_ALT1/3/5 are still missing from `segbits_int_l`. My settings were:  `--min-progress` argument to `10` instead of `50` and without the regexp. 
I don't think it was a bad choice after all. Maybe by tweaking some parameters we could force the routing to the INT TIEOFF. I will continue checking in this direction and see what I can get.

**Comment by acomodi** [comment]
Unfortunately I cannot get all the ALT_FAN?.GFAN?. I think it should be best to do a dedicated fuzzer

**Comment by litghost** [comment]
> Unfortunately I cannot get all the ALT_FAN?.GFAN?. I think it should be best to do a dedicated fuzzer

Sounds good.  Can you take that?

**Comment by acomodi** [comment]
@litghost sure, no problem. I will make a 054 fuzzer replacing the old one that has been deleted a few weeks ago

**Comment by acomodi** [comment]
This can be closed due to this other PR https://github.com/SymbiFlow/prjxray/pull/639

**Pull request closed without merging**
