### PR TITLE
Add fuzzer specialized for solving IOI_ILOGIC[01]_CLKB.IOI_IMUX2[02]_[01] pips

### PR DESCRIPTION
**Pull request by tmichalak**
This solves ILOGIC_CLKB pips that are missing and required for SymbiFlow/symbiflow-arch-defs#1220

### CODE REVIEW

**Comment by daveshah1** [comment]
Is there anything blocking this? It would be useful for my nextpnr work too.

**Comment by litghost** [comment]
I think it needs to be rebased, and make sure it is working.  @tmichalak ?

**Comment by tmichalak** [comment]
I rebased the branch on `master` however for what I recall it still was unstable so I would have to revisit this fuzzer.

**Comment by litghost** [comment]
@tmichalak What is the state of this PR?  Did this pips end up in the database?  If not, can this PR be refreshed?  Thanks.

**Comment by tmichalak** [comment]
This problem has been already solved in [PR](https://github.com/SymbiFlow/prjxray/pull/1308). Closing.

**Pull request closed without merging**
