### PR TITLE
utils: makesdf: sort the output

### PR DESCRIPTION
**Pull request by kgugala**
Signed-off-by: Karol Gugala <kgugala@antmicro.com>

### CODE REVIEW

**Comment by mithro** [comment]
Poke me when this finishes and I'll see about getting the change into the prjxray-db output.

**Comment by litghost** [comment]
> Poke me when this finishes and I'll see about getting the change into the prjxray-db output.

Poke

**Comment by mithro** [comment]
Should be live now - https://github.com/SymbiFlow/prjxray-db/commit/34ea6eb08a63d21ec16264ad37a0a7b142ff6031

**Comment by mithro** [comment]
I rebased https://github.com/SymbiFlow/prjxray/pull/835 on top of this CL and pushed it so that we can get the updated output.

**Pull request merged**
