### PR TITLE
improve hostcheck

### PR DESCRIPTION
**Pull request by dnltz**

### CODE REVIEW

**Comment by mithro** [comment]
LGTM!

**Comment by dnltz** [comment]
Artix7 timed-out again :/

**Comment by mithro** [comment]
@dnltz - Rather than doing a static sleep, I think we should do a loop. Can you apply the following patch?
```patch
diff --git a/.github/kokoro/steps/hostcheck.sh b/.github/kokoro/steps/hostcheck.sh
index 27edc2ca..6b6af011 100755
--- a/.github/kokoro/steps/hostcheck.sh
+++ b/.github/kokoro/steps/hostcheck.sh
@@ -11,19 +11,25 @@ set -e
 
 echo
 echo "========================================"
-echo "Check storage"
+echo "Waiting for storage"
 echo "----------------------------------------"
-# Wait 30 seconds to not check the storage too early.
-sleep 30
-set -x +e
-mount | grep /tmpfs
-MOUNT_RET=$?
-set +x -e
-if [[ $MOUNT_RET != 0 ]] ; then
-       echo "----------------------------------------"
-       echo "Error: No storage is mounted on /tmpfs."
-       echo "----------------------------------------"
+STORAGE_CHECK_ATTEMPTS=1
+while true; do
+       # Check that tmpfs has been mounted correctly.
+       set -x +e
+       mount | grep /tmpfs
+       MOUNT_RET=$?
+       set +x -e
+       if [[ $MOUNT_RET == 0 ]] ; then
+               break;
+       else
+               echo "----------------------------------------"
+               echo "Error: No storage is mounted on /tmpfs."
+               echo "----------------------------------------"
+               echo ""
+       fi
 
+       # Dump debugging information.
        echo "========================================"
        echo "Dmesg dump"
        echo "----------------------------------------"
@@ -65,5 +71,16 @@ if [[ $MOUNT_RET != 0 ]] ; then
        echo "----------------------------------------"
        systemctl | grep dev
 
-       exit $MOUNT_RET
-fi
+       # Fail if we have waited to long.
+       if [[ $STORAGE_CHECK_ATTEMPTS -gt 5 ]]; then
+               exit $MOUNT_RET
+       else
+               STORAGE_CHECK_ATTEMPTS = $(( $STORAGE_CHECK_ATTEMPTS + 1 ))
+       fi
+
+       # Wait for a bit before rechecking.
+       SLEEP_FOR=$(( STORAGE_CHECK_ATTEMPTS * 10 ))
+       echo ""
+       echo "Sleeping for $SLEEP_FOR seconds before trying again..."
+       sleep $SLEEP_FOR
+done
```

**Comment by dnltz** [comment]
https://github.com/SymbiFlow/prjxray/pull/1633 has the additional changes.

**Pull request closed without merging**
