### PR TITLE
Add spartan7_50 support

### PR DESCRIPTION
**Pull request by MaksRawski**
Signed-off-by: Maks Rawski <maksymilian.rawski@tutanota.com>

### CODE REVIEW

**Comment by litghost** [comment]
Which version of Vivado was this tested against?  Overall looks ok if the CI passes.

**Comment by MaksRawski** [comment]
2017.2

**Comment by litghost** [comment]
> Which version of Vivado was this tested against? Overall looks ok if the CI passes.

I'll need to add Spartan 7 to the kokoro backend, I'll do that latest today.

**Comment by MaksRawski** [comment]
Great!

**Comment by litghost** [comment]
> 2017.2

Great!   Thanks for getting this working.

**Comment by litghost** [comment]
@MaksRawski I've added the required changes to get this working on kokoro in #1535, specifically https://github.com/SymbiFlow/prjxray/pull/1535/commits/ba0ed9dba2f960b68e4d86e6963bbaf0c088466a.  In a couple hours hopefully the spartan7 CI is green!

**Comment by litghost** [comment]
Failure in CI:
```
2021-01-08T18:06:47 - xc7s50fgga484-1/051-pip-imuxlout-bypalts  - 5m47s: + echo '`define SEED 32'\''h03f77de6'
2021-01-08T18:06:47 - xc7s50fgga484-1/051-pip-imuxlout-bypalts  - 5m47s: + make -f /tmpfs/src/github/symbiflow-prjxray-presubmit-db-spartan7/utils/top_generate.mk
2021-01-08T18:06:47 - xc7s50fgga484-1/051-pip-imuxlout-bypalts  - 5m47s: ERROR: [Vivado 12-1408] Cannot set bel property of instances, Instance mydff_4 can not be placed in BFF of site SLICE_X16Y149 because the bel is occupied by roi/picorv32/count_instr_reg[61](port:). This could be caused by bel constraint conflict
2021-01-08T18:06:47 - xc7s50fgga484-1/051-pip-imuxlout-bypalts  - 5m47s: make[4]: *** [vivado.ok] Error 1
2021-01-08T18:06:47 - xc7s50fgga484-1/051-pip-imuxlout-bypalts  - 5m47s: make[3]: *** [build/1/specimen_001/OK] Error 2
2021-01-08T18:06:47 - xc7s50fgga484-1/051-pip-imuxlout-bypalts  - 5m47s: make[2]: *** [run] Error 2
2021-01-08T18:06:47 - xc7s50fgga484-1/051-pip-imuxlout-bypalts  - 5m47s: 
2021-01-08T18:06:47 - xc7s50fgga484-1/051-pip-imuxlout-bypalts  - 5m47s: --------------------------------------------------------------------------
2021-01-08T18:06:47 - xc7s50fgga484-1/051-pip-imuxlout-bypalts  - 5m47s: !Failed! @ 2021-01-08T18:06:47.118580 with exit code: 2
2021-01-08T18:06:47 - xc7s50fgga484-1/051-pip-imuxlout-bypalts  - 5m47s: --------------------------------------------------------------------------
2021-01-08T18:06:47 - xc7s50fgga484-1/051-pip-imuxlout-bypalts  - 5m47s: WARNING: Fuzzer failed!
```

Did you see something like this?  Did your run of 051-pip-imuxlout-bypalts pass?

**Comment by MaksRawski** [comment]
It worked just fine on my end, I have no idea what happened here.

**Comment by MaksRawski** [comment]
Honestly I don't think it ran 051 when I built it, my 051 folder doesn't have any build files. I ran it like in the fourth step of [the guide](https://symbiflow.readthedocs.io/projects/prjxray/en/latest/db_dev_process/newpart.html) and 051 isn't mentioned there.

**Comment by MaksRawski** [comment]
Oh yeah I just noticed that I was supposed to run `make db-spartan7-all`. Running it right now, but I guess I'm gonna get the same thing.

**Comment by litghost** [comment]
Looks like 051 was the only fuzzer that failed in the CI, but there are some jobs that run after 051.  Here is the log from the CI: https://source.cloud.google.com/results/invocations/5c0123f1-4c31-4891-bd43-017559b9cefd/log

Frankly the fact that 051 was the only failing fuzzer is a pretty good start!

**Comment by litghost** [comment]
If you want to run just the fuzzers that didn't run in the CI, you should be able to run the following:
```
make env
make -j build
source settings/spartan7.sh
make -C fuzzer_071-ppips
```

**Comment by litghost** [comment]
> Honestly I don't think it ran 051 when I built it, my 051 folder doesn't have any build files. I ran it like in the fourth step of [the guide](https://symbiflow.readthedocs.io/projects/prjxray/en/latest/db_dev_process/newpart.html) and 051 isn't mentioned there.

Worth noting that guide is for adding a part that is already in a family we support (e.g. kintex, artix, spartan).  We haven't had spartan7 support in place, which is why we are so excited for you to work on this!

**Comment by MaksRawski** [comment]
> Failure in CI:
> 
> ```
> 2021-01-08T18:06:47 - xc7s50fgga484-1/051-pip-imuxlout-bypalts  - 5m47s: + echo '`define SEED 32'\''h03f77de6'
> 2021-01-08T18:06:47 - xc7s50fgga484-1/051-pip-imuxlout-bypalts  - 5m47s: + make -f /tmpfs/src/github/symbiflow-prjxray-presubmit-db-spartan7/utils/top_generate.mk
> 2021-01-08T18:06:47 - xc7s50fgga484-1/051-pip-imuxlout-bypalts  - 5m47s: ERROR: [Vivado 12-1408] Cannot set bel property of instances, Instance mydff_4 can not be placed in BFF of site SLICE_X16Y149 because the bel is occupied by roi/picorv32/count_instr_reg[61](port:). This could be caused by bel constraint conflict
> 2021-01-08T18:06:47 - xc7s50fgga484-1/051-pip-imuxlout-bypalts  - 5m47s: make[4]: *** [vivado.ok] Error 1
> 2021-01-08T18:06:47 - xc7s50fgga484-1/051-pip-imuxlout-bypalts  - 5m47s: make[3]: *** [build/1/specimen_001/OK] Error 2
> 2021-01-08T18:06:47 - xc7s50fgga484-1/051-pip-imuxlout-bypalts  - 5m47s: make[2]: *** [run] Error 2
> 2021-01-08T18:06:47 - xc7s50fgga484-1/051-pip-imuxlout-bypalts  - 5m47s: 
> 2021-01-08T18:06:47 - xc7s50fgga484-1/051-pip-imuxlout-bypalts  - 5m47s: --------------------------------------------------------------------------
> 2021-01-08T18:06:47 - xc7s50fgga484-1/051-pip-imuxlout-bypalts  - 5m47s: !Failed! @ 2021-01-08T18:06:47.118580 with exit code: 2
> 2021-01-08T18:06:47 - xc7s50fgga484-1/051-pip-imuxlout-bypalts  - 5m47s: --------------------------------------------------------------------------
> 2021-01-08T18:06:47 - xc7s50fgga484-1/051-pip-imuxlout-bypalts  - 5m47s: WARNING: Fuzzer failed!
> ```
> 
> Did you see something like this? Did your run of 051-pip-imuxlout-bypalts pass?

After running it I got something a little different:
```
2021-01-09T05:22:02 - xc7s50fgga484-1/051-pip-imuxlout-bypalts  - 1m07s: ERROR: [Vivado 12-1408] Cannot set bel property of instances, Instance mylut_4 can not be placed in D6LUT of site SLICE_X19Y149 because the bel is occupied by roi/picorv32/i__carry__14_i_1(port:). This could be caused by bel constraint conflict
```

**Comment by mithro** [comment]
I think this was fixed in https://github.com/SymbiFlow/prjxray/pull/1534 ?

**Pull request closed without merging**
