### PR TITLE
Add some disk space checks in happy and sad paths.

### PR DESCRIPTION
**Pull request by litghost**

### CODE REVIEW

**Comment by litghost** [comment]
FYI @dnltz

**Comment by litghost** [comment]
@mithro / @tmichalak Let me know if you have another comments about this change, thanks.

**Comment by tmichalak** [comment]
> Let me know if you have another comments about this change, thanks.

Looks fine for me

**Comment by mithro** [comment]
@litghost Can we get the output of `dmesg` if the `df -h` doesn't have the `/tmpfs` mount?

**Comment by dnltz** [comment]
@mithro - I can do this tomorrow, if @litghost agrees. My idea was to also abort the run if /tmpfs is not mounted to get faster feedback and to restart the run directly.

**Comment by litghost** [comment]
> @mithro - I can do this tomorrow, if @litghost agrees. My idea was to also abort the run if /tmpfs is not mounted to get faster feedback and to restart the run directly.

Sounds good to me, thanks!

**Pull request merged**
