### PR TITLE
utils: mergedb: lock database accesses

### LINKED ISSUE #460: mergedb has issues if two fuzzers merge at the same time
If running a parallel build, there is an issue with mergedb running at the same time.

Should it do some type of locking or something?

### PR DESCRIPTION
**Pull request by kgugala**
fixes #460

### CODE REVIEW

**Comment by litghost** [comment]
Look nice and simple, I like it.  Can you add something to make clean or equiv, in case a lockfile gets left around?

**Comment by kgugala** [comment]
sure, this is good idea.
BTW this PR adds dependancy on `lockfile`, but it shouldn't be a big issue

**Comment by litghost** [comment]
Oh, lockfile is not a standard posix utility :(

**Comment by litghost** [comment]
Please update the README.md with how to acquire the lockfile program.  The apt package names does not appear to be lockfile.

**Comment by litghost** [comment]
Because it doesn't appear to be a standard utility you will likely need to update the kokoro script to get the CI to accept it.

**Comment by kgugala** [comment]
I added clean_locks target to the fuzzers Makefile

**Comment by kgugala** [comment]
hmm, `lockfile` comes with `procmail` package. `procmail` throws a dialog window asking for mail configuration

**Comment by litghost** [comment]
> hmm, `lockfile` comes with `procmail` package. During installtion `procmail` throws a dialog window asking for mail configuration

Errr, is there a smaller package?  Otherwise I'd like to take another approach.

**Comment by kgugala** [comment]
Can we use `DEBIAN_FRONTEND=noninteractive` in kokoro?

https://askubuntu.com/questions/972516/debian-frontend-environment-variable

<blockquote><div>Ask Ubuntu</div><div><strong><a href="https://askubuntu.com/questions/972516/debian-frontend-environment-variable">DEBIAN_FRONTEND environment variable</a></strong></div><div>My potential hosting provider suggests to run a command in the terminal in order to make KVM based server's OS image minimal. Since their KVM templates come with packages I will not need, I thought I </div></blockquote>

**Comment by litghost** [comment]
I'd rather not have users installing procmail just to get file locking.

**Comment by kgugala** [comment]
There is a python filelock package https://pypi.org/project/filelock/
Maybe small python locker script and filelock package in virtenv?

**Comment by kgugala** [comment]
I mean the same mechanism as we have right now, but use python locker instead `lockfile`

**Comment by litghost** [comment]
> There is a python filelock package https://pypi.org/project/filelock/
> Maybe small python locker script and filelock package in virtenv?

I'd prefer the python dependency over the procmail dependency.  

<blockquote><div> PyPI</div><div><strong><a href="https://pypi.org/project/filelock/">filelock</a></strong></div><div>A platform independent file lock.</div></blockquote>

**Comment by kgugala** [comment]
`flock` does the trick and is a standard tool. @litghost please redo the review

**Comment by litghost** [comment]
Looks good, gonna wait for a presubmit to make progress before merging.

**Pull request merged**
