### PR TITLE
Conditionally use MAP_POPULATE to support non-Linux OSes

### PR DESCRIPTION
**Pull request by HackerFoo**

### CODE REVIEW

**Comment by litghost** [comment]
I almost wonder if we need MAP_POPULATE at all?

Should we use CMake's "try_compile" for this?

**Comment by HackerFoo** [comment]
It's not clear what will happen with `MAP_PRIVATE | MAP_POPULATE` before 2.6.23. It could be a runtime error, or maybe it will just be ignored.

This change seems like the safest option, and also documents where MAP_POPULATE will apply. Otherwise I'd use:

```c
#ifndef MAP_POPULATE
#define MAP_POPULATE 0
#endif
```

**Comment by litghost** [comment]
> It's not clear what will happen with `MAP_PRIVATE | MAP_POPULATE` before 2.6.23

Fair.  I'm wondering if we should just drop `MAP_POPULATE`, if the performance improvement is small.

Maybe just drop it and see what happens to the CI build time.

**Comment by litghost** [comment]
> Looks like there was a tool failure in kokoro, re-running CI now.

Master is green again, re-running CI.

**Comment by HackerFoo** [comment]
I don't understand how this PR could change anything, since it shouldn't affect recent Linux systems at all, but I got this error for the Zynq database:

```
ERROR: 1 collisions
  0040209a_006_27: had CLBLM_R_X65Y53.CLBLM_R.SLICEL_X1.BLUT.INIT[16], got INT_R_X65Y53.INT_R.IMUX25.LOGIC_OUTS18
```

**Comment by litghost** [comment]
> I don't understand how this PR could change anything, since it shouldn't affect recent Linux systems at all, but I got this error for the Zynq database:
> 
> ```
> ERROR: 1 collisions
>   0040209a_006_27: had CLBLM_R_X65Y53.CLBLM_R.SLICEL_X1.BLUT.INIT[16], got INT_R_X65Y53.INT_R.IMUX25.LOGIC_OUTS18
> ```

That Zynq failure has been showing up intermittently: https://github.com/SymbiFlow/prjxray/issues/1246 , definitely not your issues.

**Comment by litghost** [comment]
This PR has been superceeded by #1361

**Pull request closed without merging**
