### PR TITLE
xyaml: fix import error

### PR DESCRIPTION
**Pull request by mcmasterg**

### CODE REVIEW

**Comment by mcmasterg** [comment]
this is also breaking tilegrid

**Comment by mithro** [comment]
Your running this without `env`?

**Comment by mithro** [comment]
The line https://github.com/SymbiFlow/prjxray/blob/master/utils/environment.sh#L19 should mean you can import `xjson` / `xyaml`. Can you check what your `$PYTHONPATH` is?

**Comment by mcmasterg** [comment]
Not a bug. Caused by my local screen command dropping PYTHONPATH

**Pull request closed without merging**
