### PR TITLE
030-iob: improve rdb processing for LVDS and TMDS

### PR DESCRIPTION
**Pull request by acomodi**
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>

Fixes issue found in https://github.com/SymbiFlow/prjxray/pull/1587#issuecomment-781507948

### CODE REVIEW

**Review by litghost — COMMENTED** [review]
This seems ok, just waiting for CI results.  @acomodi, what testing have you done?

**Comment by acomodi** [comment]
@litghost I have checked with some minitests with bit2fasm (display-port, litex minitests) to see whether the changed features caused problems and it seemed that everything went all right.

There have been some neg bits additions due to the merge of the "only diff" iostandards with the "normal" ones. The change can actually be seen in the zynq CI which completed (should be equal to the artix one).

When this change is pushed in prjxray-db, we will need to update some of the fasm features.

**Comment by acomodi** [comment]
Oh, actually all CIs completed while I was writing :)

**Comment by litghost** [comment]
> @litghost I have checked with some minitests with bit2fasm (display-port, litex minitests) to see whether the changed features caused problems and it seemed that everything went all right.
> 
> There have been some neg bits additions due to the merge of the "only diff" iostandards with the "normal" ones. The change can actually be seen in the zynq CI which completed (should be equal to the artix one).
> 
> When this change is pushed in prjxray-db, we will need to update some of the fasm features.

Can you please also test that LiteX and picosoc bit -> fasm and fasm -> bit (via xc-fasm2bels) work as expected?

**Comment by litghost** [comment]
Also double check the the slew features are working as expected, I see some changes in the harness JSON's, but they look ok.

**Comment by litghost** [comment]
Looks like we lost this feature:
```
-LIOB33.IOB_Y1.LVCMOS12_LVCMOS15_LVCMOS18_LVCMOS25_LVCMOS33_LVTTL.SLEW.FAST !38_16 !38_18 !38_20 !38_22 !39_17 !39_21
```

It was a pure negative feature, but it's worth making sure things make sense still.

**Comment by acomodi** [comment]
@litghost I have tested the LiteX DDR design which has many different IOSTANDARDs and SLEWs, and, starting from a working bitstream, the resulting one in the bit -> fasm -> xc-fasm2bels -> bit flow resulted to be identical and working on HW with the new IOB features changes.

There was also a bug in the process_rdb which resulted in the deletion of the pure negative feature which is now fixed.

**Pull request merged**
