### PR TITLE
fuzzers: Improve DSP fuzzer

### PR DESCRIPTION
**Pull request by daveshah1**
Still not perfect, but with this there are enough bits known that a simple combinational DSPs (at least) can go through pnr and bitgen

### CODE REVIEW

**Comment by litghost** [comment]
Overall, looks pretty good, couple things:

The following features have been removed:
```
-DSP_L.DSP48.DSP_0.SEL_MASK[1] 27_82
-DSP_L.DSP48.DSP_1.SEL_MASK[1] 27_242
```

Any idea why?

Other issue is a formatting update:
```
diff --git a/fuzzers/100-dsp-mskpat/generate.py b/fuzzers/100-dsp-mskpat/generate.py
index 2b12c69..93b3724 100644
--- a/fuzzers/100-dsp-mskpat/generate.py
+++ b/fuzzers/100-dsp-mskpat/generate.py
@@ -137,8 +137,8 @@ def run():
             #add(segmk, site, dsp, 'SEL_MASK_C', 0, params['SEL_MASK'] == quote("C"), 0, False)
             add(
                 segmk, site, dsp, 'SEL_MASK_C_ROUNDING_MODE_1', 0,
-                params['SEL_MASK'] in (quote("ROUNDING_MODE_1"), quote("C")),
-                0, False)
+                params['SEL_MASK'] in (quote("ROUNDING_MODE_1"),
+                                       quote("C")), 0, False)
             add(
                 segmk, site, dsp, 'SEL_MASK_ROUNDING_MODE_2', 0,
                 params['SEL_MASK'] in (quote("ROUNDING_MODE_2"), ), 0, False)
```

Run `make format` to fix.

**Comment by daveshah1** [comment]
> The following features have been removed:

That should be fixed in the most recent push (I didn't quite understand these bits properly)

> Other issue is a formatting update:

I ran `make format-py`, but maybe there is a yapf version issue or something? Will see how the most recent push goes down.

**Comment by litghost** [comment]
I've merged https://github.com/SymbiFlow/prjxray/pull/1212/commits/22213404a555e1cf2a522e8d46f25c363608e060 because it's pretty good.  Something to fix in a follow up is to add feature grouping, for example:

```
+DSP_L.DSP48.DSP_0.SEL_MASK_C 26_83
+DSP_L.DSP48.DSP_0.SEL_MASK_ROUNDING_MODE1 27_82
+DSP_L.DSP48.DSP_0.SEL_MASK_ROUNDING_MODE2 27_81 27_82
```

`SEL_MASK_ROUNDING_MODE2` is clearly exclusive with `SEL_MASK_ROUNDING_MODE1`, so `SEL_MASK_ROUNDING_MODE1` should be `!27_81 27_82`.  @mkurc-ant Did you merge your tag grouping stuff?  Can you show an example for on this PR?

**Comment by mkurc-ant** [comment]
@litghost Not yet. I have to move the tool to the `utils` folder. But its there, you can use it as an example: https://github.com/SymbiFlow/prjxray/pull/1186/files#diff-9d3a61968efbf5c4a6387fb27f3fd62cR1

**Pull request merged**
